# -*- coding: utf-8 -*-
"""WebScraping.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NMcYBPxenLmPbSuPrcrrTqfl0BqLpKgu
"""

import requests
from bs4 import BeautifulSoup

web=requests.get("https://help-setu.vercel.app/")
web.status_code

web.content

web.url

soup=BeautifulSoup(web.content,"html.parser")
print(soup.prettify())

soup.title

soup.title.name

soup.title.string

soup.title.parent.name


soup.p



soup.a

soup.find_all('a')

tag=soup.html

type(tag)

tag=soup.h1
print(tag)

tag=soup.a
print(tag)

tag=soup.a.string
print(tag)

tag=soup.nav
print(tag)

soup.name

soup.title.string

print(soup.body)

soup.find("h1")

soup.find_all("h1")

soup.find_all("span")

print(soup.h1.string)

print(soup)

print(soup.prettify())

print(soup.body.prettify())

print(web.url)

soup.find("div",class_="foot")

lines=soup.find_all("div")

for i in lines:
  print(i.text)

links=soup.find_all("a")

for i in links:
  print(i.get("href"))

img=soup.find_all("img")

for i in img:
  print(i.get("src"))

img

url="https://www.amazon.in/s?k=iphone&crid=161PIETK3YHR3&sprefix=iphone%2Caps%2C407&ref=nb_sb_noss_1"
headers = {'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36'}

web=requests.get(url,headers=headers)
# web.status_code

web.content